version: "3"
services:
  node:
    build: .
    command: "npm run server"
    working_dir: /home/node/app/back-end
    environment:
      - NODE_ENV=production
    expose:
      - "4000"
    ports:
      - "4000:4000"
